[2024-02-06T21:51:24.635+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-postgres-dag.create_table manual__2024-02-06T21:31:41.150201+00:00 [queued]>
[2024-02-06T21:51:24.677+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-postgres-dag.create_table manual__2024-02-06T21:31:41.150201+00:00 [queued]>
[2024-02-06T21:51:24.681+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-02-06T21:51:24.721+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_table> on 2024-02-06 21:31:41.150201+00:00
[2024-02-06T21:51:24.732+0000] {standard_task_runner.py:60} INFO - Started process 245 to run task
[2024-02-06T21:51:24.763+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-postgres-dag', 'create_table', 'manual__2024-02-06T21:31:41.150201+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/election_dag.py', '--cfg-path', '/tmp/tmp9to0o8d1']
[2024-02-06T21:51:24.773+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask create_table
[2024-02-06T21:51:24.996+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-postgres-dag.create_table manual__2024-02-06T21:31:41.150201+00:00 [running]> on host f2319e8e6bfa
[2024-02-06T21:51:25.334+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='El_mboup' AIRFLOW_CTX_DAG_ID='***-postgres-dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T21:31:41.150201+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T21:31:41.150201+00:00'
[2024-02-06T21:51:25.344+0000] {sql.py:276} INFO - Executing: 
   CREATE TABLE IF NOT EXISTS candidatures_presidentielle (
       id SERIAL PRIMARY KEY,
       prenom VARCHAR(255),
       nom VARCHAR(255),
       parti VARCHAR(255),
       satut_validation VARCHAR(50)
   );
   
[2024-02-06T21:51:25.377+0000] {base.py:83} INFO - Using connection ID '***_conn' for task execution.
[2024-02-06T21:51:25.414+0000] {base.py:83} INFO - Using connection ID '***_conn' for task execution.
[2024-02-06T21:51:25.427+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/election_dag.py", line 57, in create_candidate_table
    PostgresOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-02-06T21:51:25.471+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***-***-dag, task_id=create_table, execution_date=20240206T213141, start_date=20240206T215124, end_date=20240206T215125
[2024-02-06T21:51:25.524+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task create_table (connection to server at "***" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "***"
; 245)
[2024-02-06T21:51:25.615+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T21:51:26.120+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
