[2024-02-06T23:32:50.050+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: senegal_presidential_election_dag.save_valid_candidates_to_new_table manual__2024-02-06T22:26:56.887233+00:00 [queued]>
[2024-02-06T23:32:50.062+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: senegal_presidential_election_dag.save_valid_candidates_to_new_table manual__2024-02-06T22:26:56.887233+00:00 [queued]>
[2024-02-06T23:32:50.063+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-06T23:32:50.081+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_valid_candidates_to_new_table> on 2024-02-06 22:26:56.887233+00:00
[2024-02-06T23:32:50.093+0000] {standard_task_runner.py:60} INFO - Started process 1410 to run task
[2024-02-06T23:32:50.096+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'senegal_presidential_election_dag', 'save_valid_candidates_to_new_table', 'manual__2024-02-06T22:26:56.887233+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/election_xcom.py', '--cfg-path', '/tmp/tmpz9pfzuf4']
[2024-02-06T23:32:50.106+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask save_valid_candidates_to_new_table
[2024-02-06T23:32:50.184+0000] {task_command.py:423} INFO - Running <TaskInstance: senegal_presidential_election_dag.save_valid_candidates_to_new_table manual__2024-02-06T22:26:56.887233+00:00 [running]> on host 4775ae97916b
[2024-02-06T23:32:50.290+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='el_mboup' AIRFLOW_CTX_DAG_ID='senegal_presidential_election_dag' AIRFLOW_CTX_TASK_ID='save_valid_candidates_to_new_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T22:26:56.887233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T22:26:56.887233+00:00'
[2024-02-06T23:32:50.303+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/election_xcom.py", line 43, in save_valid_candidates_to_new_table
    serialized_candidates = [{'id': row.id, 'prenom': row.prenom, 'nom': row.nom, 'parti': row.parti, 'satut_validation': row.satut_validation} for row in candidature_validees]
TypeError: 'NoneType' object is not iterable
[2024-02-06T23:32:50.316+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=senegal_presidential_election_dag, task_id=save_valid_candidates_to_new_table, execution_date=20240206T222656, start_date=20240206T233250, end_date=20240206T233250
[2024-02-06T23:32:50.329+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task save_valid_candidates_to_new_table ('NoneType' object is not iterable; 1410)
[2024-02-06T23:32:50.358+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T23:32:50.387+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
