[2024-02-07T09:10:38.092+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_complexe_xcom_fusion_table.create_table_1 scheduled__2024-01-16T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
